CREATE TABLE USERS(
	USERID SERIAL PRIMARY KEY NOT NULL,
	DESCRIPTION TEXT,
	USERNAME CHAR(30),
	PASSWORD CHAR(30),
	EMAIL CHAR(30),
	FIRSTNAME CHAR(30),
	LASTNAME CHAR(30),
	ROLE INT,
	BIRTHDAY TIMESTAMP,
	CITY CHAR(30),
	COUNTRY CHAR(30),
	TELEPHONE CHAR(30),
	GENDER INT,
	CREATED TIMESTAMP,
	UPDATED TIMESTAMP,
	PHOTO TEXT,
	PHOTOCREATED TIMESTAMP,
	ACTIVE INT
);
CREATE TABLE GROUPS(
	GROUPID SERIAL PRIMARY KEY NOT NULL,
	NAME CHAR(30),
	DESCRIPTION TEXT,
	CREATED TIMESTAMP,
	GROUPTYPE INT,
	UPDATED TIMESTAMP
);
CREATE TABLE USERGROUP(
	GROUPID INT NOT NULL,
	USERID INT NOT NULL,
	LEVEL INT,
	CREATED TIMESTAMP,
	PRIMARY KEY(GROUPID, USERID)
);
CREATE TABLE MESSAGES(
	ID SERIAL PRIMARY KEY NOT NULL,
	RECIEVER INT,
	SENDER INT,
	MESSAGE TEXT,
	CREATED TIMESTAMP
);
CREATE TABLE SHAREDNEWS(
	ID SERIAL PRIMARY KEY NOT NULL,
	CREATED TIMESTAMP,
	SHAREDUSERID TIMESTAMP,
	GROUPID INT,
	NEWSID INT,
	DESCRIPTION TEXT
);
	

	

	
