CREATE TABLE USERS(
	USERID SERIAL PRIMARY KEY NOT NULL,
	DESCRIPTION TEXT,
	USERNAME TEXT,
	PASSWORD TEXT,
	EMAIL TEXT,
	FIRSTNAME TEXT,
	LASTNAME TEXT,
	ROLE INT,
	BIRTHDAY TIMESTAMP,
	CITY CHAR(30),
	COUNTRY TEXT,
	TELEPHONE TEXT,
	GENDER INT,
	CREATED TIMESTAMP,
	UPDATED TIMESTAMP,
	PHOTO TEXT,
	PHOTOCREATED TIMESTAMP,
	ACTIVE INT
);
CREATE TABLE GROUPS(
	GROUPID SERIAL PRIMARY KEY NOT NULL,
	NAME TEXT,
	DESCRIPTION TEXT,
	CREATED TIMESTAMP,
	GROUPTYPE INT,
	UPDATED TIMESTAMP
);
CREATE TABLE USERGROUP(
	GROUPID INT NOT NULL,
	USERID INT NOT NULL,
	LEVEL INT,
	CREATED TIMESTAMP,
	PRIMARY KEY(GROUPID, USERID)
);
CREATE TABLE MESSAGES(
	ID SERIAL PRIMARY KEY NOT NULL,
	RECIEVER INT,
	SENDER INT,
	MESSAGE TEXT,
	CREATED TIMESTAMP
);
CREATE TABLE SHAREDNEWS(
	ID SERIAL PRIMARY KEY NOT NULL,
	CREATED TIMESTAMP,
	SHAREDUSERID INT,
	GROUPID INT,
	NEWSID INT,
	DESCRIPTION TEXT
);
	

	

	
